config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    get 'welcome/hello'
    get 'welcome/about'

    resources :goals
    patch '/goals/:id/complete', to: 'goals#complete', as: :goal_complete

    root 'welcome#hello'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/goal.rb
class Goal < ApplicationRecord
    belongs_to :user

    validates :title,
        length: { maximum: 80, too_long: "%{count} characters is the maximum allowed" },
        presence: true
    validates :description,
        length: { maximum: 500, too_long: "%{count} characters is the maximum allowed" },
        presence: true
    validates :due_date, presence: true

    scope :by_status, ->(s=nil) { s.nil? ? all : where(completed: s) }

    def priority_name 
        %w[Low Medium High][priority]
    end

    def priority_icon
        arr_ico = %w[bi-arrow-down bi-arrow-up bi-arrow-up]
        arr_ico_col = %w[blue yellow red]
        "<i class=\"bi #{arr_ico[priority]}\" style=\"color: #{arr_ico_col[priority]};\"></i>".html_safe
    end

    def status_icon
        arr_ico = %w[bi-check-circle bi-check-circle-fill]
        "<i class=\"bi #{arr_ico[completed && 1 || 0]}\" style=\"color: #{completed ? 'green' : ''};\"></i>".html_safe
    end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :goals

  validates :first_name,
            length: { maximum: 127, too_long: "%{count} characters is the maximum allowed" },
            presence: true
  validates :last_name,
            length: { maximum: 127, too_long: "%{count} characters is the maximum allowed" },
            presence: true
  validates :email,
            length: { maximum: 255, too_long: "%{count} characters is the maximum allowed" },
            presence: true
  validates :encrypted_password,
            length: { maximum: 72, too_long: "%{count} characters is the maximum allowed",
                      minimum: 6, too_short: "%{count} characters is the minimum allowed" },
            presence: true

  def goal_empty?
    goals.empty?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def logout
    sign_out current_user
    redirect_to root_path, notice: 'You have been signed out.'
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: %i[show edit update complete destroy]
  #include ApplicationHelper

  def index
    @goals_count = current_user.goals.count
    @goals_completed_count = current_user.goals.by_status(true).count
    @goals_incompleted_count_count = current_user.goals.by_status(false).count
    if @goals_count > 0
      @goals = current_user.goals.by_status(params[:status])
      render
    else
      render :nogoals
    end
  end

  def new
    @goal = Goal.new
  end

  def edit 
    render :new
  end

  def create
    @goal = current_user.goals.build(goal_params)

    if @goal.save
      redirect_to goals_url, status: :created,
                  notice: "Your goal has been successfully created."
    else
      redirect_to new_goal_url, status: :unprocessable_entity,
                  alert: "Your goal has NOT been created: #{@goal.errors.full_messages}"
    end
  end

  def update
    if @goal.update(goal_params)
      redirect_to goals_url, 
        notice: "Your goal has been successfully updated."
    else
      redirect_to edit_goal_url, status: :unprocessable_entity,
        alert: "Your goal has NOT been updated: #{@goal.errors.full_messages[0]}!"
    end
  end

  def complete
    if @goal.update(goal_param_compl)
      respond_to do |format|
          format.html { render inline: helpers.goal_status_btn(@goal) }
      end
    end
  end

  def destroy
    @goal.destroy
    redirect_to goals_url, status: :see_other, 
      notice: "Your goal has been successfully deleted."
  end

  private

  def set_goal
    @goal = Goal.find(params[:id])
  end

  def goal_params
    params.require(:goal).permit(:title,:description,:priority,:due_date,completed: false)
  end

  def goal_param_compl
    params.require(:goal).permit(:completed)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def hello
    @goal_empty = Goal.count > 0 ? false : true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def goal_status_btn(goal)
        btn = "<button type=\"button\" class=\"bi bi-check-lg btn #{goal.completed ? 'btn-success' : 'btn-secondary'}\"
                data-goal-target=\"elementToInvert\"
                data-goal-completed-param=\"#{goal.completed}\"
                data-goal-url-param=\"#{goal_complete_path(goal)}\"
                data-action=\"goal#status\">#{goal.completed ? ' Completed' : ' Mark Complete'}</button>"
        btn.html_safe
    end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/goals/_goal_form.html.erb
<%= bootstrap_form_for @goal, :html => {
    :id => @goal.new_record? ? "new_goal" : "edit_goal_#{@goal.id}", name: "goal_form" }  do |f| %>

    <%= f.text_field :title, required: true %>
    <%= f.text_area :description, label: "Description", required: true  %>
    <%= f.select :priority, [['High',2],['Medium',1],['Low',0]] %>
    <%= f.date_field :due_date, :start_year => Date.current.year, required: true %>
    <br/>
<% end %>

app/views/goals/index.html.erb
<div class="container">
    <p><h5>My Goals</h5></p>
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <div class="container-fluid">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <%= link_to "All #{@goals_count}",
                        goals_path,
                        class: "nav-link #{current_page?(goals_path, check_parameters: :status) ? 'active' : ''}", "data-toggle": "tab" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Incomplete #{@goals_incompleted_count_count}",
                        goals_path(status: false),
                        class: "nav-link #{current_page?(goals_path(status: false)) ? 'active' : ''}", "data-toggle": "tab" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Completed #{@goals_completed_count}",
                        goals_path(status: true),
                        class: "nav-link #{current_page?(goals_path(status: true)) ? 'active' : ''}", "data-toggle": "tab" %>
                </li>
            </ul>
            <%= link_to "Create a Goal", new_goal_path,
                class: "btn btn-primary" %>
        </div>
    </nav>
    
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                <th scope="col">Goal Name</th>
                <th scope="col">Due Date</th>
                <th scope="col">Priority</th>
            </thead>
            <tbody>
            <% @goals.each do |goal| %>
                <tr scope="row">
                    <td class="col-sm">
                        <%= goal.status_icon %>&nbsp;&nbsp;&nbsp;
                        <%= link_to goal.title, goal %>
                    </td>
                    <td class="col-sm"><%= goal.due_date %></td>
                    <td class="col-sm">
                        <%= goal.priority_icon %>
                        <%= goal.priority_name %></td>
                </tr>
            <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/goals/new.html.erb
<div class="container">
    <h5 class="card-title"><%= @goal.new_record? ? "Create a Goal" : "Edit a Goal" %></h5>
    <div class="card">
        <div class="card-body">
            <%= render 'goal_form', goal: @goal %>
        </div>
    </div>
</div>
<footer class="footer mt-auto py-3 bg-light">
    <ul class="nav justify-content-center">
        <li>
            <%= link_to "Cancel", goals_path, class: "btn btn-secondary" %>
            <input type="submit" 
                form=<%= @goal.new_record? ? "new_goal" : "edit_goal_#{@goal.id}" %> 
                value=<%= @goal.new_record? ? "Create" : "Save" %>
                class="btn btn-primary" />
        </li>
    </ul>
</footer>

app/views/goals/nogoals.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <p><h5>My Goals</h5></p>
    </div>
    <div class="col-12 text-center">
      <div class="col-md-12", style="margin-top: 250px;">
        <%= image_tag "nogoal.png", class: "img-fluid" %>
        <p><h7>You have no goals. Not going to lie, this is a bit sad.</h7></p>
      </div>
      <div class="btn" style="margin-top: 10px;">
        <%= link_to "Create a Goal",
                    { controller: "goals", action: "new" },
                    class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/goals/show.html.erb
<div class="container">
  <%= link_to "<  My Goals", goals_path, class: "nav-link active" %>
  <br/>
  <nav class="navbar navbar-expand-sm navbar-light bg-light">
    <div class="container-fluid">
      <div data-controller="goal">
        <%= goal_status_btn(@goal) %>
      </div>
    </div>
    <ul class="navbar-nav ml-auto">
      <i class="bi bi-pencil-square"></i>
      <li class="nav-item">
        <%= link_to "Edit", edit_goal_path(@goal),
                    class: "nav-link" %>
      </li>
      <i class="bi-trash"></i>
      <li class="nav-item">
        <%= link_to "Delete", @goal,
                    data: { turbo_confirm: 'Are you sure you want to delete this goal?', turbo_method: :delete },
                    class: "nav-link" %>
      </li>
    </ul>
  </nav>
  <div class="container">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title mb-3"><%= @goal.title %></h5>

        <div class="row">
          <div class="col-sm">
            <i class="bi bi-calendar-date"></i> <span class="text-grey" style="color: grey;">Due date:</span> <%= @goal.due_date %>
          </div>
          <div class="col-sm">
            <span class="text-grey" style="color: grey;">Priority:</span><%= @goal.priority_icon %><%= @goal.priority_name %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm mt-3">
            <span class="text-grey" style="color: grey;">Description:</span> <%= @goal.description %>
          </div>
          <div class="col-sm"></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="shadow-sm bg-white rounded">
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand">
                <%= image_tag 'lil.png', size: "30x30", alt: "" %>
                BeFocused
            </a>
            <ul class="navbar-nav navbar-right">
                <li>
                    <% unless current_page?(root_path)  %>
                        <%= link_to " About", root_path,
                            class: "nav-link active bi bi-info-circle" %>
                    <% end %>
                </li>
              <li>
                  <% if user_signed_in? %>
                    <%= button_to ' Sign out', destroy_user_session_path, class: "btn bi bi-arrow-right-square", method: :delete %>
                  <% end %>
              </li>
            </ul>
        </div>
    </nav>
</div>

<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
    </symbol>
    <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
        <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
    </symbol>
</svg>
<% if notice.present? %>
    <div class="alert alert-success text-center d-lg-flex alert-dismissible" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
        <%= notice %>
    </div>
<% end %>
<% if alert.present? %>
    <div class="alert alert-warning text-center d-lg-flex alert-dismissible" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Warning:"><use xlink:href="#exclamation-triangle-fill"/></svg>
        <%= alert %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <%= javascript_include_tag 'password_toggle'%>
    <%#= javascript_include_tag 'password_bar'%>
    <title>Befocused</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body class="d-flex flex-column h-100">
    <% if user_signed_in? %>
    <header>
      <%= render 'layouts/navbar' %>
    </header>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/welcome/_about.html.erb
<h2 class="card-title">Self-development goals tracker</h2>
<br/>
<h5 class="card-title">
    BeFocused is a convenient centralized personal space for any students,
    learners or other interested in self-education and self-development people.
</h5>
<br/>
<p class="card-text">
    Moreover, setting goals in the right way can help you achieve them! 
    goal should be SMART and here's what it means:
</p>
<p class="card-text">
    Specific: Well defined, clear and unambiguous
</p>
<p class="card-text">
    Measurable: With specific criteria that measure your progress towards
    the accomplishment of the goal
</p>
<p class="card-text">
    Achievable: Attainable and not impossible to achieve
</p>
<p class="card-text">
    Realistic: Within reach, realistic, and relevant to your life purpose
</p>
<p class="card-text">
    Timely: With a clearly defined timeline, including a starting date and a
    target date. The purpose is to create urgency.
</p>  

app/views/welcome/hello.html.erb
<div class="container">
  <div class="text">
    <div class="row g-0">
      <div class="col-md-6">
        <div class="card-body">
          <%= render 'about' %>
          <ul class="nav nav-pills">
            <li class="nav-item">
              <% if user_signed_in? %>
                <%= link_to(current_user.goal_empty? ? "Get Started" : "Back to My Goals", goals_path, class: "nav-link active" ) %>
              <% else %>
                <%= link_to "Get Started", new_user_registration_path, class: "nav-link active" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-6">
        <%= image_tag "big.png", class: "img-fluid" %>
      </div>
    </div>
  </div>
</div>